### ISSUE TITLE
Emacs fails to load names package

### ISSUE THREAD

**Issue by mrkkrp** [Malabarba/names#18]
Hi! Recently I got a whim to test my personal configuration with Travis CI. This allowed me to catch something strange. In order to test my configuration Travis first setups Emacs trunk, then it executes very [simple Python script](https://github.com/mrkkrp/dot-emacs/blob/master/test-startup.py).

Now, in my configuration I first install all necessary packages, [like this](https://github.com/mrkkrp/dot-emacs/blob/master/init.el#L76-L85).

This is where interesting things happen. It fails like this: [travis log](https://travis-ci.org/mrkkrp/dot-emacs#L208).

First, I can reproduce it on my local machine. It seems like package `names` is installed but something bad happens when Emacs tries to load it. Why it happens on `names`? Other packages before it are installed smoothly.

Second, if I start the same script immediately after the fail, the rest of it works fine -- all other packages are downloaded and everything is OK.

Third, I did some testing. I use this command to invoke emacs:

```
emacs -nw --batch --eval "..."
```

It doesn't fail without `--batch` option. I can call the script and end up inside started Emacs with all packages installed.

----

This is curious. It seems like some sort of bug, but I'm not sure that it's not my fault. What do you think? Why does it happen only with `--batch` option and only when Emacs is trying to activate `names` package?

**Comment by Malabarba** [comment]
Thanks for reporting this. I see what the problem is, and it's not your fault. ;-)
I just pushed a fix to the dev branch, and if it passes the tests I'll merge to master and you can test your stuff again.

**Comment by Malabarba** [comment]
And it's merged. Let me know if it worked.

**Comment by mrkkrp** [comment]
Perfect! Now everything is fine (all packages are installed successfully, it still fails, but now it's certainly my work to fix that) ;-)
